### ISSUE TITLE
Bot - Create

### ISSUE THREAD

**Issue by johnervan** [Geboto/bot-platform#1]
- [x] User Input:
1. Bot Name
2. Bot Description

- [x] Auto Generated:
1. Bot ID
2. Platform Activation Status (For now just FB) --> Default False
3. Facebook Bot Credentials
4. Bot Creation Date
5. Bot Modified Date

**Comment by jaeoheeail** [comment]
Confirmed Auto Generated:
1. Bot ID
2. User ID
3. Creation Date
4. Modified Date
5. Array of Story IDs

Should there be an array of "slave bot" IDs? these slave bots are pegged to a messaging platform:
1. Slave-Bot ID
2. Master-Bot ID
3. Creation Date
4. Modified Date
5. Platform specific Credentials in JSON
6. Activation Status
