### ISSUE TITLE
mb_persister.get_bot_config(master_bot_id) returns null

### ISSUE THREAD

**Issue by johnervan** [Geboto/bot-platform#30]

**Comment by johnervan** [comment]
The problem lies in bot creation:
I'm not giving you the user's user id. 
I can only give you the user's username(email). You might need to query the database for the user id

**Comment by jaeoheeail** [comment]
Okay I think I know how to fix it

**Comment by jaeoheeail** [comment]
@johnervan I am not too sure what you mean actually by not giving me the user's user_id.

For this method, isn't what you are giving me the master_bot_id as seen from the method signature?

**Comment by jaeoheeail** [comment]
i think the method you are referring to is create_master_bot?

**Comment by johnervan** [comment]
My bad sorry!
