### ISSUE TITLE
Set number of bots available for each account

### ISSUE THREAD

**Issue by johnervan** [Geboto/bot-platform#39]

**Comment by jaeoheeail** [comment]
credentials = {NUM_BOTS: 2,
                        ACCESS_TOKENS: {{AGENT_NAME: <account_id>_1, TOKEN: <token>, USED: false},{AGENT_NAME: <account_id>_2, TOKEN: <token>, USED: false}}
                       }

**Comment by jaeoheeail** [comment]
Scrapped, created new table api_ai_access_token
