### ISSUE TITLE
Updating of Database for FB Integration

### ISSUE THREAD

**Issue by johnervan** [Geboto/bot-platform#8]

**Comment by jaeoheeail** [comment]
I need account_id, master_bot_id and slave_bot_id when you send the form over with the slave_bot credentials

this is for edit

default:
var credentials = {TYPE: "FB",
                        WEBHOOK_URL: "",
                        PAGE_ACCESS_TOKEN: "",
                        FACEBOOK_APP_ID: ""
                      };
